version: "3.9"

services:
  database:
    container_name: "database"
    image: "library/postgres:12.2-alpine"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - sapphire
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    depends_on:
      - database
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    image: "dpage/pgadmin4"
    networks:
      - sapphire
    ports:
      - "8080:80"
    volumes:
      - ./data/pgadmin:/root/.pgadmin

  # Redis cache / session storage
  redis:
    image: "redis:6.0.10"
    ports:
      - "6379:6379"
    networks:
      - sapphire
    restart: always

networks:
  sapphire:
    driver: bridge

volumes:
  data: {}
