version: "3.9"

services:
  database:
    image: "library/postgres:13.2"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./pgsql/load-extensions.sql:/docker-entrypoint-initdb.d/load-extensions.sql

  # Redis cache / session storage
  redis:
    image: "redis:6.0.10"
    depends_on:
      - database
    ports:
      - "6379:6379"
    restart: always

networks:
  default:
    external:
      name: sapphire

volumes:
  pgdata: {}
